# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://51.21.67.44:3306/clink?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: clink
    password: clink1234
  thymeleaf:
    cache: false
  servlet:
    multipart:
      location: /home/ubuntu/uploads/Attachments #공지사항 이미지 업로드 경로
      maxFileSize: 10MB
      maxRequestSize: 100MB


  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
